In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv("Iris.csv", header=None)
df

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
col= ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm", "Species"]
df.columns=col
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

# 1.Create data subsets for different species

In [4]:
df["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [5]:
df_setosa= df[df["Species"]=="Iris-setosa"]
df_setosa.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
df_versicolor= df[df["Species"]=="Iris-versicolor"]
df_versicolor.head()

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
50            7.0           3.2            4.7           1.4  Iris-versicolor
51            6.4           3.2            4.5           1.5  Iris-versicolor
52            6.9           3.1            4.9           1.5  Iris-versicolor
53            5.5           2.3            4.0           1.3  Iris-versicolor
54            6.5           2.8            4.6           1.5  Iris-versicolor

In [7]:
df_virginica= df[df["Species"]=="Iris-virginica"]
df_virginica.head()

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
100            6.3           3.3            6.0           2.5  Iris-virginica
101            5.8           2.7            5.1           1.9  Iris-virginica
102            7.1           3.0            5.9           2.1  Iris-virginica
103            6.3           2.9            5.6           1.8  Iris-virginica
104            6.5           3.0            5.8           2.2  Iris-virginica

# 2.Merge two subsets

In [8]:
df_setosa_versicolor= pd.concat([df_setosa, df_versicolor])
df_setosa_versicolor

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0             5.1           3.5            1.4           0.2      Iris-setosa
1             4.9           3.0            1.4           0.2      Iris-setosa
2             4.7           3.2            1.3           0.2      Iris-setosa
3             4.6           3.1            1.5           0.2      Iris-setosa
4             5.0           3.6            1.4           0.2      Iris-setosa
..            ...           ...            ...           ...              ...
95            5.7           3.0            4.2           1.2  Iris-versicolor
96            5.7           2.9            4.2           1.3  Iris-versicolor
97            6.2           2.9            4.3           1.3  Iris-versicolor
98            5.1           2.5            3.0           1.1  Iris-versicolor
99            5.7           2.8            4.1           1.3  Iris-versicolor

[100 rows x 5 columns]

In [9]:
print("setosa shape: ", df_setosa.shape)
print("versicolor shape: ", df_versicolor.shape)
print("merge shape: ", df_setosa_versicolor.shape)

setosa shape:  (50, 5)
versicolor shape:  (50, 5)
merge shape:  (100, 5)

In [10]:
df_merged= pd.concat([df_setosa, df_versicolor, df_virginica])
df_merged

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [11]:
print("setosa shape: ", df_setosa.shape)
print("versicolor shape: ", df_versicolor.shape)
print("virginica shape: ", df_virginica.shape)
print("merge shape: ", df_merged.shape)

setosa shape:  (50, 5)
versicolor shape:  (50, 5)
virginica shape:  (50, 5)
merge shape:  (150, 5)

# 3. Sort Data Petal Length

In [13]:
df_sort= df.sort_values(by=["PetalLengthCm"])
df_sort

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
22             4.6           3.6            1.0           0.2     Iris-setosa
13             4.3           3.0            1.1           0.1     Iris-setosa
14             5.8           4.0            1.2           0.2     Iris-setosa
35             5.0           3.2            1.2           0.2     Iris-setosa
36             5.5           3.5            1.3           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
131            7.9           3.8            6.4           2.0  Iris-virginica
105            7.6           3.0            6.6           2.1  Iris-virginica
117            7.7           3.8            6.7           2.2  Iris-virginica
122            7.7           2.8            6.7           2.0  Iris-virginica
118            7.7           2.6            6.9           2.3  Iris-virginica

[150 rows x 5 columns]

# 4. Transposing Data

In [16]:
df_transpose= df.transpose()
df_transpose

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
SepalLengthCm,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
SepalWidthCm,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
PetalLengthCm,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
PetalWidthCm,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
Species,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

# 5.Melting Data to long format

In [17]:
df_melted= pd.melt(df, id_vars=["SepalLengthCm", "PetalLengthCm", "Species"], var_name="Metric", value_name="value")
df_melted

     SepalLengthCm  PetalLengthCm         Species        Metric  value
0              5.1            1.4     Iris-setosa  SepalWidthCm    3.5
1              4.9            1.4     Iris-setosa  SepalWidthCm    3.0
2              4.7            1.3     Iris-setosa  SepalWidthCm    3.2
3              4.6            1.5     Iris-setosa  SepalWidthCm    3.1
4              5.0            1.4     Iris-setosa  SepalWidthCm    3.6
..             ...            ...             ...           ...    ...
295            6.7            5.2  Iris-virginica  PetalWidthCm    2.3
296            6.3            5.0  Iris-virginica  PetalWidthCm    1.9
297            6.5            5.2  Iris-virginica  PetalWidthCm    2.0
298            6.2            5.4  Iris-virginica  PetalWidthCm    2.3
299            5.9            5.1  Iris-virginica  PetalWidthCm    1.8

[300 rows x 5 columns]

In [19]:
df_melted1= pd.melt(df, id_vars=["SepalLengthCm", "PetalLengthCm"], var_name="Metric", value_name="value")
df_melted1

     SepalLengthCm  PetalLengthCm        Metric           value
0              5.1            1.4  SepalWidthCm             3.5
1              4.9            1.4  SepalWidthCm             3.0
2              4.7            1.3  SepalWidthCm             3.2
3              4.6            1.5  SepalWidthCm             3.1
4              5.0            1.4  SepalWidthCm             3.6
..             ...            ...           ...             ...
445            6.7            5.2       Species  Iris-virginica
446            6.3            5.0       Species  Iris-virginica
447            6.5            5.2       Species  Iris-virginica
448            6.2            5.4       Species  Iris-virginica
449            5.9            5.1       Species  Iris-virginica

[450 rows x 4 columns]

# 6.Casting data to wide format

In [20]:
df_casted= pd.pivot_table(df, index=["Species"])
df_casted

                 PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm
Species
Iris-setosa              1.464         0.244          5.006         3.418
Iris-versicolor          4.260         1.326          5.936         2.770
Iris-virginica           5.552         2.026          6.588         2.974

In [21]:
df_casted1= pd.pivot_table(df, index=["Species", "PetalLengthCm"], values=["PetalWidthCm"])
df_casted1

                               PetalWidthCm
Species         PetalLengthCm
Iris-setosa     1.0                0.200000
                1.1                0.100000
                1.2                0.200000
                1.3                0.257143
                1.4                0.216667
                1.5                0.221429
                1.6                0.285714
                1.7                0.350000
                1.9                0.300000
Iris-versicolor 3.0                1.100000
                3.3                1.000000
                3.5                1.000000
                3.6                1.300000
                3.7                1.000000
                3.8                1.100000
                3.9                1.233333
                4.0                1.220000
                4.1                1.200000
                4.2                1.325000
                4.3                1.300000
                4.4                1.325000
                4.5                1.485714
                4.6                1.400000
                4.7                1.420000
                4.8                1.600000
                4.9                1.500000
                5.0                1.700000
                5.1                1.600000
Iris-virginica  4.5                1.700000
                4.8                1.800000
                4.9                1.866667
                5.0                1.800000
                5.1                1.971429
                5.2                2.150000
                5.3                2.100000
                5.4                2.200000
                5.5                1.900000
                5.6                2.050000
                5.7                2.300000
                5.8                1.866667
                5.9                2.200000
                6.0                2.150000
                6.1                2.233333
                6.3                1.800000
                6.4                2.000000
                6.6                2.100000
                6.7                2.100000
                6.9                2.300000

In [23]:
df_casted2= pd.pivot_table(df, index=["Species", "PetalLengthCm"])
df_casted2

                               PetalWidthCm  SepalLengthCm  SepalWidthCm
Species         PetalLengthCm
Iris-setosa     1.0                0.200000       4.600000      3.600000
                1.1                0.100000       4.300000      3.000000
                1.2                0.200000       5.400000      3.600000
                1.3                0.257143       4.842857      3.228571
                1.4                0.216667       4.916667      3.333333
                1.5                0.221429       5.128571      3.535714
                1.6                0.285714       4.914286      3.342857
                1.7                0.350000       5.400000      3.600000
                1.9                0.300000       4.950000      3.600000
Iris-versicolor 3.0                1.100000       5.100000      2.500000
                3.3                1.000000       4.950000      2.350000
                3.5                1.000000       5.350000      2.300000
                3.6                1.300000       5.600000      2.900000
                3.7                1.000000       5.500000      2.400000
                3.8                1.100000       5.500000      2.400000
                3.9                1.233333       5.533333      2.633333
                4.0                1.220000       5.780000      2.480000
                4.1                1.200000       5.700000      2.833333
                4.2                1.325000       5.725000      2.900000
                4.3                1.300000       6.300000      2.900000
                4.4                1.325000       6.275000      2.750000
                4.5                1.485714       5.900000      2.928571
                4.6                1.400000       6.400000      2.900000
                4.7                1.420000       6.440000      3.060000
                4.8                1.600000       6.350000      3.000000
                4.9                1.500000       6.600000      2.800000
                5.0                1.700000       6.700000      3.000000
                5.1                1.600000       6.000000      2.700000
Iris-virginica  4.5                1.700000       4.900000      2.500000
                4.8                1.800000       6.100000      2.900000
                4.9                1.866667       6.000000      2.833333
                5.0                1.800000       6.000000      2.400000
                5.1                1.971429       6.142857      2.900000
                5.2                2.150000       6.600000      3.000000
                5.3                2.100000       6.400000      2.950000
                5.4                2.200000       6.550000      3.250000
                5.5                1.900000       6.566667      3.033333
                5.6                2.050000       6.366667      2.933333
                5.7                2.300000       6.766667      3.266667
                5.8                1.866667       6.800000      2.833333
                5.9                2.200000       6.950000      3.100000
                6.0                2.150000       6.750000      3.250000
                6.1                2.233333       7.433333      3.133333
                6.3                1.800000       7.300000      2.900000
                6.4                2.000000       7.900000      3.800000
                6.6                2.100000       7.600000      3.000000
                6.7                2.100000       7.700000      3.300000
                6.9                2.300000       7.700000      2.600000